ServerEvents.recipes(event => {
    function replace(old, replacement){
        event.replaceInput(
            {input: old},
            old,
            replacement
        )

        event.replaceOutput(
            {output: old},
            old,
            replacement
        )
    }

    replace('divinerpg:arlemite_ingot', 'gtceu:arlemite_ingot')
    replace('divinerpg:rupee_ingot', 'gtceu:rupee_ingot')
    replace('divinerpg:realmite_ingot', 'gtceu:realmite_ingot')
    replace('divinerpg:bloodgem', 'gtceu:bloodgem_gem')
    replace('divinerpg:torridite_ingot', 'gtceu:torridite_ingot')
    replace('tardis_refined:zeiton_ingot', 'gtceu:zeiton_ingot')
    replace('tardis_refined:zeiton_block', 'gtceu:zeiton_block')
    replace('tardis_refined:zeiton_nugget', 'gtceu:zeiton_nugget')
    replace('rftoolsbase:dimensionalshard', 'gtceu:dimensional_shard_gem')
    replace('mysticalagriculture:prosperity_shard', 'gtceu:prosperity_shard_gem')
    replace('mysticalagriculture:inferium_essence', 'gtceu:inferium_essence_dust')
    replace('mysticalagriculture:soulium_dust', 'gtceu:soulium_dust_dust')
    replace('enderio:copper_alloy_ingot', 'gtceu:copper_alloy_ingot')
    replace('enderio:redstone_alloy_ingot', 'gtceu:redstone_alloy_ingot')
    replace('enderio:conductive_alloy_ingot', 'gtceu:conductive_alloy_ingot')
    replace('enderio:pulsating_alloy_ingot', 'gtceu:pulsating_alloy_ingot')
    replace('enderio:dark_steel_ingot', 'gtceu:dark_steel_ingot')
    replace('enderio:photovoltaic_composite', 'gtceu:photovoltaic_composite_dust')
    replace('enderio:dark_steel_ingot', 'gtceu:dark_steel_ingot')
    replace('theabyss:loran','gtceu:loran_gem')
    replace('theabyss:garnite_ingot', 'gtceu:garnite_ingot')
    replace('theabyss:ignisithe_gem', 'gtceu:ignisithe_gem')
    replace('theabyss:glacerythe_gem', 'gtceu:glacerythe_gem')
    replace('theabyss:aberythe_gem', 'gtceu:aberythe_gem')
    replace('theabyss:incorythe_gem', 'gtceu:incorythe_gem')
    replace('good_nights_sleep:raw_spectrite', 'gtceu:raw_spectrite')
    replace('good_nights_sleep:spectrite_ingot', 'gtceu:spectrite_ingot')
    replace('good_nights_sleep:raw_spectrite_block', 'gtceu:raw_spectrite_block')
    replace('gtceu:raw_spectrite_block', 'gtceu:spectrite_block')
    replace('good_nights_sleep:positite', 'gtceu:positite_gem')
    replace('good_nights_sleep:positite_block', 'gtceu:positite_block')
    replace('good_nights_sleep:zitrite_ingot', 'gtceu:zitrite_ingot')
    replace('good_nights_sleep:zitrite_block', 'gtceu:zitrite_block')
    replace('good_nights_sleep:raw_zitrite', 'gtceu:raw_zitrite')
    replace('good_nights_sleep:negatite', 'gtceu:negatite_gem')
    replace('good_nights_sleep:negatite_block', 'gtceu:negatite_block')
    replace('blue_skies:aquite', 'gtceu:aquite_gem')
    replace('blue_skies:aquite_block', 'gtceu:aquite_block')
    replace('blue_skies:raw_aquite', 'gtceu:raw_aquite')
    replace('blue_skies:raw_aquite_block', 'gtceu:raw_aquite_block')
    replace('blue_skies:diopside_gem', 'gtceu:diopside_gem')
    replace('blue_skies:diopside_block', 'gtceu:diopside_block')
    replace('blue_skies:charoite', 'gtceu:charoite_gem')
    replace('blue_skies:raw_charoite', 'gtceu:raw_charoite')
    replace('blue_skies:charoite_block', 'gtceu:charoite_block')
    replace('blue_skies:raw_charoite_block', 'gtceu:raw_charoite_block')
    replace('blue_skies:falsite_ingot', 'gtceu:falsite_ingot')
    replace('blue_skies:raw_falsite', 'gtceu:raw_falsite')
    replace('blue_skies:falsite_block', 'gtceu:falsite_block')
    replace('blue_skies:raw_falsite_block', 'gtceu:raw_falsite_block')
    replace('blue_skies:falsite_nugget', 'gtceu:falsite_nugget')
    replace('blue_skies:ventium_ingot', 'gtceu:ventium_ingot')
    replace('blue_skies:ventium_block', 'gtceu:ventium_block')
    replace('blue_skies:raw_ventium_block', 'gtceu:raw_ventium_block')
    replace('blue_skies:ventium_nugget', 'gtceu:ventium_nugget')
    replace('blue_skies:raw_ventium', 'gtceu:raw_ventium')
    replace('blue_skies:horizonite_ingot', 'gtceu:horizonite_ingot')
    replace('blue_skies:horizonite_block', 'gtceu:horizonite_block')
    replace('blue_skies:raw_horizonite', 'gtceu:raw_horizonite')
    replace('blue_skies:horizonite_nugget', 'gtceu:horizonite_nugget')
    replace('blue_skies:raw_horizonite_block', 'gtceu:raw_horizonite_block')
    replace('aether:ambrosium_shard', 'gtceu:ambrosium_gem')
    replace('aether:ambrosium_block', 'gtceu:ambrosium_block')
    replace('aether:zanite_gemstone', 'gtceu:zanite_gem')
    replace('aether:zanite_block', 'gtceu:zanite_block')
})
